import type { CapacitorConfig } from "@capacitor/cli";

/**
 * Capacitor wraps the static Next.js export into a native Android app.
 * Only Android is targeted right now (see notes in lib/platform.ts) —
 * we don't run `cap add ios` because iOS doesn't actually gain
 * anything from the wrapper that the PWA doesn't already do, and
 * shipping to TestFlight requires a paid Apple Developer account.
 *
 * The android/ directory generated by `npx cap add android` is
 * committed to the repo so Vercel / CI builds don't need an Android
 * SDK. Local APK builds need Android Studio (or a standalone Gradle
 * + Android command-line SDK) — that part is documented in README.
 */
const config: CapacitorConfig = {
  appId: "lol.pepinho.ytplayer",
  appName: "YT Player",
  // Next.js writes the static export to ./out when output: 'export'
  // is on; scripts/build-capacitor.mjs runs the export build and
  // then `cap sync android` copies ./out → android/app/src/main/
  // assets/public for bundling into the APK.
  webDir: "out",
  server: {
    // androidScheme="https" makes localStorage / OPFS / fetch all
    // behave as if served from https origin, which matches what the
    // PWA expects (and matches what the worker's CORS allow-list
    // already permits).
    androidScheme: "https",
  },
  android: {
    // Permit HTTP traffic ONLY in debug builds (release builds enforce
    // cleartext-traffic prohibition by default). The PWA itself uses
    // HTTPS to the worker, but during dev you may want to point
    // NEXT_PUBLIC_WORKER_API_URL at http://10.0.2.2:3001 from the
    // emulator — this opens that door without weakening release.
    allowMixedContent: false,
  },
};

export default config;
